import Head from 'next/head'
import { useRouter } from 'next/router'
import { PropsWithChildren, useContext, useEffect } from 'react'
import { useCookies } from 'react-cookie'
import MarFashionProvider, {
  MarFashionContext,
} from 'src/context/MarFashionProvider'

export default function BaseLayout({ children }: PropsWithChildren) {
  const router = useRouter()
  const [cookies] = useCookies(['user'])

  useEffect(() => {
    if (cookies.user?.role === 'ADMIN') {
      router.push('/admin', undefined, { shallow: true })
      console.log('ini ke admin')
    }
    if (cookies.user?.role === 'KARYAWAN') {
      router.push('/karyawan', undefined, { shallow: true })
      console.log('ini ke karyawan')
    }

    router.push('/guess', undefined, { shallow: true })
  }, [])

  return (
    <>
      <Head>
        <title>Mar Fashion Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MarFashionProvider>{children}</MarFashionProvider>
    </>
  )
}
