import Head from 'next/head'
import { PropsWithChildren } from 'react'
import { ToastContainer } from 'react-toastify'
import MarFashionProvider from 'src/context/MarFashionProvider'

export default function BaseLayout({ children }: PropsWithChildren) {
  return (
    <>
      <Head>
        <title>Mar Fashion Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MarFashionProvider>{children}</MarFashionProvider>
      <ToastContainer />
    </>
  )
}
